export const USER_STATE_CHANGE = "USER_STATE_CHANGE"
export const POSTS_STATE_CHANGE = "POSTS_STATE_CHANGE"
export const USER_POST_STATE_CHANGE = "USER_POST_STATE_CHANGE"
export const GET_BOOKS = "GET_BOOKS"
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE"

